# version: '3.8'


volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
  # sqlvolume:

services:
  next-app:
    container_name: next-emd-app
    build:
      context: ./
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public
    #   - ./prisma:/app/prisma
    #   - ./types:/app/types
    #   - node_modules:/app/node_modules
    restart: always
    ports:
      - 3000:3000
    networks:
      - emd_network
    environment:
      # - SYSNAME=EGAT
      - DATABASE_URL=mysql://root:MYSQL_ROOT_PASSWORD@db:3306/meeting_room
  db:
    container_name: db
    image: mysql:8.4.2
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: meeting_room
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - ./mysql/src:/var/lib/mysql
    networks:
      - emd_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3001:80"
    restart: always
    environment:
      TZ: "Asia/Bangkok"
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - emd_network
      
networks:
  emd_network:
    driver: bridge